services:
  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api-node
      - water-gate-frontend
    networks:
      - app_network

  api-node:
    build: ./services/api-node
    container_name: api_node
    expose:
      - "3000"
    networks:
      - app_network

  water-gate-frontend:
    build:
      context: ./services/water-gate-frontend
    container_name: water_gate_frontend
    expose:
      - "80"
    networks:
      - app_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network: